[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# Root configuration for tools only.
# To install the development environment, run: pip install -r dev-requirements.txt

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli = true
log_cli_level = "INFO"